services:

  openbao:
    image: openbao/openbao:2.6.0

    container_name: openbao

    restart: unless-stopped

    cap_add:
      - IPC_LOCK

    volumes:
      - ./config.hcl:/openbao/config/config.hcl
      - ./data:/openbao/data

    environment:
      BAO_ADDR: https://openbao.agropartners.com
    
    networks:
      - monitoring
    
    command: server -config=/openbao/config/config.hcl

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openbao.rule=Host(`openbao.agropartners.com`)"
      - "traefik.http.routers.openbao.entrypoints=websecure"
      - "traefik.http.routers.openbao.tls=true"
      - "traefik.http.services.openbao.loadbalancer.server.port=8200"

networks:
  monitoring:
    external: true
