api:
  dashboard: true
  insecure: false

entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"

providers:

  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: monitoring

  file:
    directory: /etc/traefik/dynamic
    watch: true


log:
  level: INFO


accessLog: {}
